  <header>
    <nav class="nav-bar">
      <input type="checkbox" name="menu-btn" id="menu-btn">
      <label for="menu-btn"><span><i class="fa-solid fa-bars"></i></span></label>
      <ul class="nav-links" id="nav-list">
        <li><a href="./index.php"><span class="icon"><i class="fa-solid fa-house"></i></span>Home</a></li>
      </ul>
      <a class="manage-button" href="./manage.php" class="active"><span class="icon"><i class="fa-solid fa-toolbox"></i></span>Manage</a> 
    </nav>
  </header>