<footer class="footer">
    <div class="footer-row">
      <div class="footer-col">
        <div class="contact-us">
          <h4>Contact Us</h4>
          <a href="https://github.com/minhnnguyen003/assign1" target="_blank"><i
              class="fa-brands fa-github brand-icon"></i></a>
        </div>

      </div>
      <div class="footer-col">
        <h3>Members</h3>
        <ul class="footer-list">
          <li class="footer-list-item"><a href="mailto:101224555@student.swin.edu.au" class="footer-list-anchor"
              target="_blank">Daniel Cornelius Wong Yui Herng</a></li>
          <li class="footer-list-item"><a href="mailto:103535741@student.swin.edu.au" class="footer-list-anchor"
              target="_blank">Md Arefin Newaz Sojol</a></li>
          <li class="footer-list-item"><a href="mailto:103831821@student.swin.edu.au" class="footer-list-anchor"
              target="_blank">Ahmed Fuzail Mohamed Imran</a></li>
          <li class="footer-list-item"><a href="mailto:103486496@student.swin.edu.au" class="footer-list-anchor"
              target="_blank">Viet Dung Tran</a></li>
          <li class="footer-list-item"><a href="mailto:103534696@student.swin.edu.au" class="footer-list-anchor"
              target="_blank">Minh Nhat Nguyen</a></li>
        </ul>
      </div>
      <div class="footer-col">
        <h3>Contact details</h3>
        <ul class="footer-list">
          <li class="footer-list-item"><a href="mailto:101224555@student.swin.edu.au" class="footer-list-anchor"
              target="_blank">101224555@student.swin.edu.au</a></li>
          <li class="footer-list-item"><a href="mailto:103535741@student.swin.edu.au" class="footer-list-anchor"
              target="_blank">103535741@student.swin.edu.au</a></li>
          <li class="footer-list-item"><a href="mailto:103831821@student.swin.edu.au" class="footer-list-anchor"
              target="_blank">103831821@student.swin.edu.au</a></li>
          <li class="footer-list-item"><a href="mailto:103486496@student.swin.edu.au" class="footer-list-anchor"
              target="_blank">103486496@student.swin.edu.au</a></li>
          <li class="footer-list-item"><a href="mailto:103534696@student.swin.edu.au" class="footer-list-anchor"
              target="_blank">103534696@student.swin.edu.au</a></li>
        </ul>
      </div>
    </div>
  </footer>