<nav class="left-pane">
        <form class="search-pane" method="get" action="./login.php">
            <input type="text" placeholder="Search">
            <button type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>

        <div class="menu-button">
            <i class="fa-solid fa-chalkboard-user"></i>
            <span>Dashboard</span>
        </div>
        <div class="menu-button">
            <i class="fa-solid fa-filter"></i>
            <span>Filter</span>
        </div>
        <div class="menu-button">
            <i class="fa-solid fa-chart-line"></i>
            <span>Chart</span>
        </div>
        <hr>
        <div class="menu-button" id="logout-btn">
            <i class="fa-solid fa-right-from-bracket"></i>
            <span>Log out</span>
        </div>
    </nav>