  <header>
    <nav class="nav-bar">
      <input type="checkbox" name="menu-btn" id="menu-btn">
      <label for="menu-btn"><span><i class="fa-solid fa-bars"></i></span></label>
      <ul class="nav-links" id="nav-list">
        <li><a href="./index.php"><span class="icon"><i class="fa-solid fa-house"></i></span>Home</a></li>
        <li><a href="./topic.php"><span class="icon"><i class="fa-solid fa-lightbulb"></i></span>Topic</a></li>
        <li><a href="./quiz.php"><span class="icon"><i class="fa-solid fa-circle-question"></i></span>Quiz</a></li>
        <li><a href="./enhancement.php" class="active"><span class="icon"><i
                class="fas fa-sliders-h"></i></span>Enhancement</a></li>
      </ul>
    </nav>
  </header>